name: Cost Optimization Report

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  cost-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate Cost Report
        run: |
          echo "# Daily Cost Report" > cost_report.md
          echo "**Date**: $(date)" >> cost_report.md
          echo "" >> cost_report.md
          az resource list --resource-group Identity-Lab-RG --output table >> cost_report.md
          echo "" >> cost_report.md
          echo "## Estimated Costs" >> cost_report.md
          echo "- Log Analytics: ~\$5" >> cost_report.md
          echo "- Sentinel: ~\$3" >> cost_report.md
          echo "- Logic Apps: ~\$1" >> cost_report.md
          echo "- Key Vault: ~\$0 (free tier)" >> cost_report.md
          echo "- **Total: ~\$9/month**" >> cost_report.md

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: cost-report
          path: cost_report.md
